version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8196:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: akcio23/backend:latest
    depends_on:
      - mysql
    ports:
      - "8195:8195"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASS: password
      DB_NAME: mydb
    restart: unless-stopped

  frontend:
    image: akcio23/frontend:latest
    depends_on:
      - backend
    ports:
      - "8197:80"
    restart: unless-stopped

volumes:
  mysql_data:
