version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "8194:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: akcio23/projeto:latest
    container_name: node_app
    restart: unless-stopped
    ports:
      - "8195:8195"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
