version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8197:3306"

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "8195:8195"
    environment:
      DB_HOST: mysql

  frontend:
    build: ./frontend
    ports:
      - "8196:80"
